import { Geography } from '../types/census.types';

export const STATES: Geography[] = [
  { name: 'Alabama', fipsCode: '01' },
  { name: 'Alaska', fipsCode: '02' },
  { name: 'Arizona', fipsCode: '04' },
  { name: 'Arkansas', fipsCode: '05' },
  { name: 'California', fipsCode: '06' },
  { name: 'Colorado', fipsCode: '08' },
  { name: 'Connecticut', fipsCode: '09' },
  { name: 'Delaware', fipsCode: '10' },
  { name: 'Florida', fipsCode: '12' },
  { name: 'Georgia', fipsCode: '13' },
  { name: 'Hawaii', fipsCode: '15' },
  { name: 'Idaho', fipsCode: '16' },
  { name: 'Illinois', fipsCode: '17' },
  { name: 'Indiana', fipsCode: '18' },
  { name: 'Iowa', fipsCode: '19' },
  { name: 'Kansas', fipsCode: '20' },
  { name: 'Kentucky', fipsCode: '21' },
  { name: 'Louisiana', fipsCode: '22' },
  { name: 'Maine', fipsCode: '23' },
  { name: 'Maryland', fipsCode: '24' },
  { name: 'Massachusetts', fipsCode: '25' },
  { name: 'Michigan', fipsCode: '26' },
  { name: 'Minnesota', fipsCode: '27' },
  { name: 'Mississippi', fipsCode: '28' },
  { name: 'Missouri', fipsCode: '29' },
  { name: 'Montana', fipsCode: '30' },
  { name: 'Nebraska', fipsCode: '31' },
  { name: 'Nevada', fipsCode: '32' },
  { name: 'New Hampshire', fipsCode: '33' },
  { name: 'New Jersey', fipsCode: '34' },
  { name: 'New Mexico', fipsCode: '35' },
  { name: 'New York', fipsCode: '36' },
  { name: 'North Carolina', fipsCode: '37' },
  { name: 'North Dakota', fipsCode: '38' },
  { name: 'Ohio', fipsCode: '39' },
  { name: 'Oklahoma', fipsCode: '40' },
  { name: 'Oregon', fipsCode: '41' },
  { name: 'Pennsylvania', fipsCode: '42' },
  { name: 'Rhode Island', fipsCode: '44' },
  { name: 'South Carolina', fipsCode: '45' },
  { name: 'South Dakota', fipsCode: '46' },
  { name: 'Tennessee', fipsCode: '47' },
  { name: 'Texas', fipsCode: '48' },
  { name: 'Utah', fipsCode: '49' },
  { name: 'Vermont', fipsCode: '50' },
  { name: 'Virginia', fipsCode: '51' },
  { name: 'Washington', fipsCode: '53' },
  { name: 'West Virginia', fipsCode: '54' },
  { name: 'Wisconsin', fipsCode: '55' },
  { name: 'Wyoming', fipsCode: '56' },
  { name: 'District of Columbia', fipsCode: '11' },
];